---
- hosts: localhost
  become: true
  tasks:
    - name: Load Docker image
      ansible.builtin.command:
        cmd: docker load -i /tmp/weather-app.tar

    - name: Docker login
      docker_login:
        username: "{{ DOCKER_USERNAME }}" 
        password: "{{ DOCKER_PASSWORD }}"

    - name: Docker push
      docker_image:
        path: ./{{ IMAGE_NAME }}
        name: "{{ IMAGE_NAME }}"
        source: local
        force: yes

    - name: Docker pull
      docker_image:
        name: "{{ IMAGE_NAME }}"
        source: registry

    - name: Docker run
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ IMAGE_NAME }}"
        restart: always
        state: started
        ports:
          - "3000:3000"

    - name: Docker logout
      docker_logout: