version: '3.7'
services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather-app

  weather-app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"