apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
        address = ":80"
      [entryPoints.websecure]
        address = ":443"
    [providers.kubernetesIngress]
      ingressClass = "traefik"
    [certificatesResolvers.default.acme]
      email = "yumotoayaka@gmail.com"
      storage = "acme.json"
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "web"
