apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"weather-app","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"weather-app"}},"template":{"metadata":{"labels":{"app":"weather-app"}},"spec":{"containers":[{"env":[{"name":"API_KEY","valueFrom":{"secretKeyRef":{"key":"API_KEY","name":"weather-app-secret"}}}],"image":"ayakayu/weather-app:1.0.0","name":"weather-app","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2024-10-24T08:41:41Z"
  generation: 5
  name: weather-app
  namespace: prod
  resourceVersion: "604362"
  uid: b90137e1-f9bb-4b75-81ad-8db7e13d8ea9
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weather-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-app
    spec:
      containers:
      - env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: API_KEY
              name: weather-app-secret
        image: ayakayu/weather-app:1.0.0
        imagePullPolicy: IfNotPresent
        name: weather-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-10-25T07:55:21Z"
    lastUpdateTime: "2024-10-25T07:55:30Z"
    message: ReplicaSet "weather-app-56f9b47f69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-28T19:52:25Z"
    lastUpdateTime: "2024-10-28T19:52:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
