apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificates.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificates.secretName }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.certificates.dnsNames }}
    - {{ . }}
    {{- end }}
 