apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.apiKeySecretName }}
              key: API_KEY
        volumeMounts:
        - name: nginx-tls
          mountPath: /etc/ssl/certs/tls.crt
          subPath: tls.crt
          readOnly: true
        - name: nginx-tls-key
          mountPath: /etc/ssl/private/tls.key
          subPath: tls.key
      volumes:
      - name: nginx-tls
        secret:
          secretName: {{ .Values.ingress.secretName }}  
      - name: nginx-tls-key
        secret:
          secretName: {{ .Values.ingress.secretName }} 