apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secretName }} 
  namespace: {{ .Release.Namespace | quote }}
data:
  tls.crt: {{ .Values.tls.cert | quote }}  
  tls.key: {{ .Values.tls.key | quote }}    
type: kubernetes.io/tls
