apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-speaker
subjects:
- kind: ServiceAccount
  name: speaker
  namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: metallb-speaker
  apiGroup: rbac.authorization.k8s.io