apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-speaker-role
rules:
- apiGroups: ["apps", "core", "discovery", "metallb.io"]
  resources: ["pods", "services", "nodes", "endpoints", "endpointslices", "servicel2statuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["selfsubjectreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectaccessreviews", "selfsubjectrulesreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-speaker-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-speaker-role
subjects:
- kind: ServiceAccount
  name: metallb-speaker
  namespace: metallb-system