app:
  name: nginx-app
  replicas: 2
  image: ayakayu/weather-app:1.0.0
  containerPort: 3000

service:
  name: nginx-service
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  protocol: TCP
  selector:
    app: nginx-app

ingress:
  name: nginx-ingress
  namespace: prod
  clusterIssuer: letsencrypt-prod
  host: finalexam.ayaka-m.cloudns.biz
  secretName: nginx-app-tls

tls:
  enabled: true  
  name: nginx-app-tls
  cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6RENDQWJRQ0NRQ1AzTCtJdFRXTldqQU5CZ2txaGtpRzl3MEJBUXNGQURBb01TWXdKQVlEVlFRRERCMW0KYVc1aGJHVjRZVzB1WVhsaGEyRXRiUzVqYkc5MVpHNXpMbUpwZWpBZUZ3MHlOREV3TWpZd09ETTNNRE5hRncweQpOVEV3TWpZd09ETTNNRE5hTUNneEpqQWtCZ05WQkFNTUhXWnBibUZzWlhoaGJTNWhlV0ZyWVMxdExtTnNiM1ZrCmJuTXVZbWw2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0UFdkbDM4RUd4MGkKdXhFTlpobk1CcHZmOXFDbi9RcExkZENGdWtmdmN2MHI4SWVMWEJOWml0RDEwUzQ4THZRSnR1Vml3bGlwemtRZgpDRVhDQ3RveHgwY2JRSkZaWENpanVUVzNvZURwbG1XZ25XdnRGcHRwcU5QdUdjWUtEVnFmcEQ4WXZzVjdxa015Cm9kZWVNVmh3V3M4K3NFYzJ3YndKSWhZNzZGNlpWbnZ0RGNLOUpySUc4dGJLY2FqeFhVK1ZZSHhHTnVVK3E5UTgKU0FWZnZMdE0yd1Vid24vNjBLcUdQcEU1VWZWMENKbEd2SjVDcDJUSGpvNVJ6bDhyaXlqQlc0d0NFL1M3NjBVeAo2bjZCcE9TeXY2NTVUTlc2SFpqQWdJTjh5MUFUY2I5dnA2STBQWVIycmhaV3VVN1JPZGpSRmI4STljai9uYTZECjk0Y1pNVktYZFFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFKOG0xWHltS1czMGdIQ3pUWExySkcKT0R3M2JVOUxOS1gzL0o0SmNSQTFFT3BFWm9iTWpZY2F3T0FSV0RKL0dOMjRvcnhGdUwrZCt2Q2piMy9BYTRaNApucFFJNE0zbGFZKzBoZjNtR2VwdHA3VS9KVDUyNnNJLzRQWEJIRURmNDVOUVRLc3ovRkR5WjJDMWJVczN2MUN6Cmx0YWk5ekZjTzhOR3ExTWhBUDd6ejd1bkJLYTQvV1lYMXQxbE1GMG13UmQ3SjUxZVhLUDIzRzdUVVNKLzN3UEYKYlNNT1hCczJ1aFdtUWpkV04wOGRxSWc0a1hsSzkyS0hyL0dzT3hWMCtkcm54d1FpYWsyc3JCRkMxVHNGYUthNApldDdaOXhaOG1OOURnaVcvOVZ0VTIzV09xaG9ldW82NTM1WVh2b3RKZlB4LzFjaG1JVUtTcnRtMXVwNGF1djRKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNFBXZGwzOEVHeDBpdXhFTlpobk1CcHZmOXFDbi9RcExkZENGdWtmdmN2MHI4SWVMClhCTlppdEQxMFM0OEx2UUp0dVZpd2xpcHprUWZDRVhDQ3RveHgwY2JRSkZaWENpanVUVzNvZURwbG1XZ25XdnQKRnB0cHFOUHVHY1lLRFZxZnBEOFl2c1Y3cWtNeW9kZWVNVmh3V3M4K3NFYzJ3YndKSWhZNzZGNlpWbnZ0RGNLOQpKcklHOHRiS2NhanhYVStWWUh4R051VStxOVE4U0FWZnZMdE0yd1Vid24vNjBLcUdQcEU1VWZWMENKbEd2SjVDCnAyVEhqbzVSemw4cml5akJXNHdDRS9TNzYwVXg2bjZCcE9TeXY2NTVUTlc2SFpqQWdJTjh5MUFUY2I5dnA2STAKUFlSMnJoWld1VTdST2RqUkZiOEk5Y2ovbmE2RDk0Y1pNVktYZFFJREFRQUJBb0lCQVFDYkVOTnpsVXRJUVZvcQpab084NkhWWjdPS0J4NVprZDA4eXcrMGFUZkhCYXNCNkNZVEhrRkw5dkRKbDRaLzhvWjE4cER2aVNXbXJWQXVzCkVTSERoMG9lMm1YdnFRRlc1SENPLzNjNEw2ZjBVdE5YRUFrYXQwQXE3d05HWXR1VS91M2lNdGdrMEU0QlBGYlAKZHFpRnpUZU5jU1ArTU9pT3ZNWHk2QzZkYTIvNVN5SnNIMVUxWkFYWEZOY0h4MDI1cHg1VFRaOG4wUlNlTFRaZgpsK21ZU1gxS2VwVk56dGFLazMxRXdhUkZnQ1pyOE1RSnc0R1hPcTVWTWw1dEtHa2hSTjVneEE2dVIvWkZFekRXCll3SXhtaHYxelYwamFTVnRwUUJuWkxtQjVvRWpjWHZsZEcrdmlqOWVMOGtTeTRnUWd5U3N2SXQzSm1nbDJWd3QKQW5UTmE5b0JBb0dCQVBMVVdPUHdjZHRrTVc1WHRoYXpMODhuaHhKbnltVWhvWUIrWi8xT3NSeElLTENXZHJlSAo2b3pWK2FGeFRUTEZlOGF0Y3JhNUdmMWN2Qi82R3hPcVN4TStOdFMzNExtMk1NSFNpYUt6aVlkOW90K2R4TTBICjVxMDRuejRUZGhyL3FsaEI4Uk1tZURBRXh0aENtNUM0Ly9IcFB3REpQaU96amVXMFBEVENLcFgxQW9HQkFPMHAKSlRROEJLbEdsUmhqNi8wZWh4MTQvT1UyaEpYSG81NnBPaVBONlQ2OFBiYkxQdDBVaGlhTW4xekVEZVB0dWQ4VwozN3BReE9iUUdvUmk4OXJOaVV3THp2QXplNXpQWncraEVSM296Wm9vcFFmWlJXNHV0bHAvNUFOaCtHSmU1dmorCnMxOWViWkNtcHVMKytTUmNpZGl5Z2pJTndzUTV4YXBFMGFzSkRZdUJBb0dCQUlvSDVLTmsrUU54dDV0MlpqNFAKQ3gwZzVlbXpiOXYrdXZQMFpwNFpqaGw2ZHc2eDZMZTRuYjRDbjR5Q2dCUmRKMWV2SG1iNVh1bWpQaGliTGFzSApBUGZtUkhxMEx4ekJrSU9NYnNvNmJmSERtOEtxeHNTWk9pbTY1dUg5WkFSQzBneXJKeUx3bWg4SmlCSkVBblBJCmhVeDRmbVN2QUJDQkx5YWtSaGpqU2h2RkFvR0JBS24xL2NLa2JKYS9qYVF3SC9TRGgwTlk3S3g3MktMYXN1akcKMEhMT1k2VGhGTDFHaFNPOVRMS2R2cXVsbVdyS2VKVm5lQ2kzTDVWV2VGcDk2OUxYejloZThndjBhVmNrei9CRQpkdGJmZTFGS1paTHRZN09sNkd1TkVlUld0c0lRenlpTXFCSGx3MUdTRFRIS2x0UTNPVmJCLzBwTjBGSCtNU2xvCkxuYUxnMWlCQW9HQUJRS3RDLzI1S1d1NTRHZGpLR3RmQWptOVJZNGhuV2x3Sy9Lc3NIbU1UcGoxQTF2ZWlRZkkKNEFQeERaakZnank3dy9Ob2Z3Q0VQQWhwajE5SUxuZHNNdU9DbElBMU9NZjFWS2g0azhrOVF4cnZ1dFdLRjNhdwozdWRNdTVPcHFGWHN4enlHVWhmc2ZTKzBhOGV0U21tNWh4dzhpRUZBWmxYaHJZV09mT2lNYXBJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

pvc:
  name: nginx-ingress-pvc
  storage: 10Gi
  storageClassName: local-path

hpa:
  name: nginx-ingress-hpa
  minReplicas: 2
  maxReplicas: 4
  averageUtilization: 70

secrets:
  apiKeySecretName: weather-app-secret

pod:
  name: weather-app-pod

clusterIssuer:
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory
  email: yumotoayaka@gmail.com
  privateKeySecretRef: letsencrypt-prod

certificates:
  enabled: true  
  name: nginx-app-tls 
  dnsNames:
    - finalexam.ayaka-m.cloudns.biz
  secretName: nginx-app-tls