name: Build, Push Docker Image, and Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub 
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          # Use Dockerfile
          docker build -t ayakayu/weather-app:1.0.0 .
          if [ $? -ne 0 ]; then
            echo "Error during docker build"
            exit 1
          fi

          # Push builded image
          docker push ayakayu/weather-app:1.0.0

      - name: Logout from Docker Hub 
        run: docker logout
      
      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Authenticate with k3s cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Upgrade Helm chart
        run: |
          helm upgrade weather-app-chart ./weather-app-chart --install --namespace default
