name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub 
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker-compose build
          if [ $? -ne 0 ]; then
            echo "Error during docker-compose build"
            exit 1
          fi
          IMAGE_ID=$(docker images -q final-project_weather-app)
          if [ -z "$IMAGE_ID" ]; then
            echo "Error: Image not found"
            exit 1
          fi
          docker tag $IMAGE_ID ayakayu/weather-app:1.0.0
          docker save -o weather-app.tar ayakayu/weather-app:1.0.0
          docker push ayakayu/weather-app:1.0.0

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: weather-app.tar

      - name: Logout from Docker Hub 
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i "localhost," -c local deploy.yml
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ayakayu/weather-app:1.0.0
          CONTAINER_NAME: my-weather-app