name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: |
          sudo docker-compose build
          if [ $? -ne 0 ]; then
            echo "Error during docker-compose build"
            exit 1
          fi
          sudo docker tag weather-app:latest ayakayu/weather-app:1.0.0
          sudo docker push ayakayu/weather-app:1.0.0
      - name: Logout from Docker Hub
        run: docker logout 